### ISSUE TITLE
app.render is not a function

### ISSUE THREAD

**Issue by youhosi** [NodeBB-Community/nodebb-plugin-recent-cards#38]
```
TypeError: app.render is not a function
    at /var/www/forum/node_modules/nodebb-plugin-recent-cards/library.js:75:7
    at renderCards (/var/www/forum/node_modules/nodebb-plugin-recent-cards/library.js:151:3)
    at /var/www/forum/node_modules/async/dist/async.js:473:16
    at next (/var/www/forum/node_modules/async/dist/async.js:5329:29)
    at /var/www/forum/node_modules/async/dist/async.js:969:16
    at /var/www/forum/src/topics/index.js:50:4
    at nextTask (/var/www/forum/node_modules/async/dist/async.js:5324:14)
    at next (/var/www/forum/node_modules/async/dist/async.js:5331:9)
    at /var/www/forum/node_modules/async/dist/async.js:969:16
    at /var/www/forum/node_modules/async/dist/async.js:473:16
    at next (/var/www/forum/node_modules/async/dist/async.js:5329:29)
    at /var/www/forum/node_modules/async/dist/async.js:969:16
    at /var/www/forum/node_modules/async/dist/async.js:473:16
    at next (/var/www/forum/node_modules/async/dist/async.js:5329:29)
    at /var/www/forum/node_modules/async/dist/async.js:969:16
    at /var/www/forum/src/topics/index.js:149:4 {"error":{},"stack":"TypeError: app.render is not a function\n    at /var/www/forum/node_modules/nodebb-plugin-recent-cards/library.js:75:7\n    at renderCards (/var/www/forum/node_modules/nodebb-plugin-recent-cards/library.js:151:3)\n    at /var/www/forum/node_modules/async/dist/async.js:473:16\n    at next (/var/www/forum/node_modules/async/dist/async.js:5329:29)\n    at /var/www/forum/node_modules/async/dist/async.js:969:16\n    at /var/www/forum/src/topics/index.js:50:4\n    at nextTask (/var/www/forum/node_modules/async/dist/async.js:5324:14)\n    at next (/var/www/forum/node_modules/async/dist/async.js:5331:9)\n    at /var/www/forum/node_modules/async/dist/async.js:969:16\n    at /var/www/forum/node_modules/async/dist/async.js:473:16\n    at next (/var/www/forum/node_modules/async/dist/async.js:5329:29)\n    at /var/www/forum/node_modules/async/dist/async.js:969:16\n    at /var/www/forum/node_modules/async/dist/async.js:473:16\n    at next (/var/www/forum/node_modules/async/dist/async.js:5329:29)\n    at /var/www/forum/node_modules/async/dist/async.js:969:16\n    at /var/www/forum/src/topics/index.js:149:4","exception":true,"date":"Sat Dec 01 2018 09:45:53 GMT+0100 (GMT+01:00)","process":{"pid":11106,"uid":1002,"gid":105,"cwd":"/var/www/forum","execPath":"/usr/bin/node","version":"v10.14.0","argv":["/usr/bin/node","/var/www/forum/app.js"],"memoryUsage":{"rss":176705536,"heapTotal":136454144,"heapUsed":103826936,"external":633130}},"os":{"loadavg":[1.7861328125,0.95458984375,0.3876953125],"uptime":515232},"trace":[{"column":7,"file":"/var/www/forum/node_modules/nodebb-plugin-recent-cards/library.js","function":null,"line":75,"method":null,"native":false},{"column":3,"file":"/var/www/forum/node_modules/nodebb-plugin-recent-cards/library.js","function":"renderCards","line":151,"method":null,"native":false},{"column":16,"file":"/var/www/forum/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/var/www/forum/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/var/www/forum/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":4,"file":"/var/www/forum/src/topics/index.js","function":null,"line":50,"method":null,"native":false},{"column":14,"file":"/var/www/forum/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/var/www/forum/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/var/www/forum/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":16,"file":"/var/www/forum/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/var/www/forum/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/var/www/forum/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":16,"file":"/var/www/forum/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/var/www/forum/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/var/www/forum/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":4,"file":"/var/www/forum/src/topics/index.js","function":null,"line":149,"method":null,"native":false}]}

```

**Comment by barisusakli** [comment]
Are you running latest core?

**Comment by youhosi** [comment]
yes, updated today

**Comment by barisusakli** [comment]
should be fixed here, https://github.com/NodeBB/NodeBB/commit/cb7c2d8c28a34ddebcea7ff48d8671d1ba174f93
