### ISSUE TITLE
Error: Failed to lookup view

### ISSUE THREAD

**Issue by BlackFayah** [NodeBB-Community/nodebb-plugin-recent-cards#41]
After installing, I went to Extend >Widgets, but there I got this error: `Failed to lookup view "admin/plugins/nodebb-plugin-recent-cards/widget" in views directory "/root/nodebb/build/public/templates"`.

The complete log:
```
2019-03-22T14:01:50.317Z [4567/17793] - [31merror[39m: /api/admin/extend/widgets
Failed to lookup view "admin/plugins/nodebb-plugin-recent-cards/widget" in views directory "/root/nodebb/build/public/templates" {"view":{"defaultEngine":"tpl","ext":".tpl","name":"admin/plugins/nodebb-plugin-recent-cards/widget","root":"/root/nodebb/build/public/templates"},"stack":"Error: Failed to lookup view \"admin/plugins/nodebb-plugin-recent-cards/widget\" in views directory \"/root/nodebb/build/public/templates\"\n    at Function.render (/root/nodebb/node_modules/express/lib/application.js:580:17)\n    at Function.router.render (/root/nodebb/src/routes/index.js:96:14)\n    at Object.plugin.defineWidgets [as method] (/root/nodebb/node_modules/nodebb-plugin-recent-cards/library.js:51:6)\n    at /root/nodebb/src/plugins/hooks.js:136:12\n    at /root/nodebb/node_modules/async/dist/async.js:2516:9\n    at replenish (/root/nodebb/node_modules/async/dist/async.js:1011:17)\n    at iterateeCallback (/root/nodebb/node_modules/async/dist/async.js:995:17)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at /root/nodebb/node_modules/async/dist/async.js:2518:13\n    at /root/nodebb/node_modules/async/dist/async.js:473:16"}
```

**Comment by BlackFayah** [comment]
Apparently the rebuilding didn't work so well yesterday, because rebuilding today fixed the error...
